### PR TITLE
Upgrade wgpu-profiler

### PR DESCRIPTION
**Pull request by DJMcNab**
Fixes https://github.com/linebender/vello/issues/678

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@DJMcNab This can be changed to 0.18.2 now and should be able to land!

**Review by waywardmonkeys — COMMENTED** [review]
Well, this doesn't crash anymore on macOS for me ... but now it dies a lot with the negative `Duration`. But that's how it is on macOS for now...

**Comment by DJMcNab** [comment]
Dies? It shouldn't crash with a negative duration, it should display the duration as negative, I think?

What's the panic message?

**Comment by waywardmonkeys** [comment]
```
thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/time.rs:957:23:
cannot convert float seconds to Duration: value is negative
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:264:5
   3: core::time::Duration::from_secs_f64::panic_cold_display
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic.rs:101:13
   4: core::time::Duration::from_secs_f64
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/time.rs:957:23
   5: with_winit::stats::draw_gpu_profiling
             at ./examples/with_winit/src/stats.rs:316:41
   6: <with_winit::VelloApp as winit::application::ApplicationHandler<with_winit::UserEvent>>::window_event
             at ./examples/with_winit/src/lib.rs:529:25
```

**Comment by waywardmonkeys** [comment]
Just tried with v0.2.1 and it definitely happens more often (almost constantly) now. Of course, the only thing that it is tracking is the render_to_texture, so it is only take some 300 microseconds or so.

**Review by waywardmonkeys — APPROVED** [review]
Go for it.

**Pull request merged**
