### PR TITLE
Update ARCHITECTURE.md

### LINKED ISSUE #577: Update ARCHITECTURE.md
`ARCHITECTURE.md` is not up to date anymore because of #563 (and maybe other things? just had that in mind when mindlessly browsing through the repo)
`/src/` doesn't have `cpu_shaders/` and `shaders/` anymore.

### PR DESCRIPTION
**Pull request by DasLixou**
Closes #577 

I wonder if we should also include the "next 3 months roadmap" under the `Roadmap` section, but it seems like the document is still read/write for everyone and I have a bad feeling just putting that in like that.

### CODE REVIEW

**Review by xStrom — APPROVED** [review]
Thanks!

**Comment by DasLixou** [comment]
why does `typos` ci not run?

**Comment by xStrom** [comment]
Because it's a new check that was just added. You can get it to run by rebasing on `main`.

**Comment by DasLixou** [comment]
I'll still wait for responses in office hours of whether putting in the roadmap or not

**Comment by xStrom** [comment]
As discussed at office hours, let's not link the document. Next week or so we'll try to create github issues based on that roadmap, and once that is done we can write some short summary with links to issues into that section.

**Pull request merged**
