### PR TITLE
Don't dispatch workgroups with no elements (CPU side)

### LINKED ISSUE #637: IOS app crash 0.2.1
IOS app crashes on launch with the following error:

```
-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:1054: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
```

Previously tested working version: vello 0.1.0 (with bevy_vello 0.3.3)

Initially discussed [_here_](https://github.com/linebender/bevy_vello/issues/67)

Does anyone know how I can fix this?

### PR DESCRIPTION
**Pull request by DJMcNab**
This should fix #637. Note this hack should be removed once the issue is fixed in upstream wgpu.

### CODE REVIEW

**Review by Philipp-M — APPROVED** [review]
I have no iOS device to test this, but the changes look reasonable to me when looking at the error output.

**Comment by DJMcNab** [comment]
This also passes our newish test suite (incl. #630), so I'm reasonably happy to merge.

**Comment by waywardmonkeys** [comment]
Is there a link to the upstream bug?

**Comment by waywardmonkeys** [comment]
Oh, found it.

**Comment by DJMcNab** [comment]
The upstream bug in wgpu? I've not looked for one - I asked @AngeloMateus to create one.

**Pull request merged**
