### PR TITLE
Update to wgpu 0.17.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is a draft as it won't land until `bevy` updates to use `wgpu` 0.17.

This disables the `with_bevy` example for now so that we can see that everything else passes the CI checks.

I've run it on Windows with the `with_winit` example and the SVG tiger and things looked okay to me. (A tiger showed up.)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Related Zulip thread: https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/WGPU.200.2E17.20plans

**Comment by dfrg** [comment]
Thanks! This looks great and I’d like to go ahead and land it now without waiting on bevy support as it allows us to push other more important work forward.

If you mark it ready for review, I’ll stamp it and we can get it merged.

**Comment by waywardmonkeys** [comment]
I've marked it as ready for review, but there was discussion during office hours that led to the idea that this wouldn't land until Bevy was ready, I think ...

but up to you (or we wait for this week's office hours)!

**Review by dfrg — APPROVED** [review]
I saw approved in the office hours agenda and assumed someone else stamped this already. Feel free to merge!

**Pull request merged**
